ddrescue: fix uclibc compile
Fixes compile failure with uclibc [1] because of missing stdio.h include:

  In file included from io.cc:28:0:
  block.h:219:22: error: ‘FILE’ has not been declared
     int write_mapfile( FILE * f = 0, const bool timestamp = false,

[1] http://autobuild.buildroot.net/results/4ac0754f1cc5ea934d6437e89d1f4906fb3fd0a8

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>