package/netatalk: bump version to 3.1.11
Building 3.1.9 still fails after removing patch 0002:

volume.c:383:26: error: 'ldap_config_valid' undeclared (first use in this function)
                     if (!ldap_config_valid || vol->v_flags & AFPVOL_NONETIDS)

Bumping to 3.1.11 solves the problem.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>