python-hpack: fix build breakage due to UTF-8 formatted file
UTF-8 formatted file breaks installations on some systems:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    long_description=open('README.rst').read() + '\n\n' + open('HISTORY.rst').read(),
  File "/home/peko/autobuild/instance-1/output/target/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1125: ordinal not in range(128)

This patch replaces '§' with 'S' meaning 'Section' and hence converts file to plain ASCII.

Fixes:

  http://autobuild.buildroot.net/results/4189b2ddcd3d59c629af78e4d455a29c77f8c683/

Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>
[Thomas: add autobuilder reference.]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>