trinity: not available on musl
After fixing following build failures with musl:

* error: unknown type name __uint32_t and __uint64_t
* error: unknown type name pid_t and uid_t
* error: fatal error: bits/sockaddr.h: No such file or directory

it fails with

  fds/files.c: In function 'file_tree_callback':
  fds/files.c:172:10: error: 'FTW_CONTINUE' undeclared (first use in this function)
     return FTW_CONTINUE;
            ^
  fds/files.c:172:10: note: each undeclared identifier is reported only once for each function it appears in
  fds/files.c:178:10: error: 'FTW_SKIP_SUBTREE' undeclared (first use in this function)
     return FTW_SKIP_SUBTREE;
            ^
  fds/files.c:185:10: error: 'FTW_STOP' undeclared (first use in this function)
     return FTW_STOP;
            ^
  fds/files.c: In function 'open_fds_from_path':
  fds/files.c:197:26: error: 'FTW_ACTIONRETVAL' undeclared (first use in this function)
    int flags = FTW_DEPTH | FTW_ACTIONRETVAL | FTW_MOUNT;

As per ftw man-page, flag FTW_ACTIONRETVAL is specific to glibc. It is
not available on musl. Since package uses it unconditionally, we mark
it not available on musl.

Fixes:
  http://autobuild.buildroot.net/results/cb4/cb4a665746652679487dee2c2e4bca881be3724b/

Cc: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
Reviewed-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>